name: GitHub Workflow

on:
 workflow_dispatch:

env:
  LIST_VARIABLE: 'element1,element2,element3'

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Iterate over list elements
        run: |
          LIST_VARIABLE=${{ env.LIST_VARIABLE }}
          IFS=',' read -ra LIST_ARRAY <<< "$LIST_VARIABLE"
          for element in "${LIST_ARRAY[@]}"; do
            echo "Element: $element"
            # Perform actions using the element as needed
          done







