# This workflow is used to run pytest on the test python file

name: execute-pytest

on:
 workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
env:
  token: ${{ secrets.TOKEN }}
  REPO: 'frst_automation,new_test_repo'

jobs:
  job-execute-pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install PyGithub
        pip install graphqlclient

    - name: Run python!
      run: |
        python environ.py
